title: "Computational Bioinformatics"
description: "ðŸš€ Exploring novel therapeutic targets through multi-omics approaches..."
baseurl: ""
url: "https://progistar.github.io"
theme: minima
markdown: kramdown