title: "Choi Lab â€” Computational Proteogenomics"
description: "Exploring novel therapeutic peptides through multi-omics approaches."
baseurl: ""
url: "https://choilab.netlify.app"
theme: minima
markdown: kramdown
